/*CREAR TABLA PARA MANEJO DE USUARIOS*/
CREATE TABLE rol(
    id int NOT NULL AUTO_INCREMENT,
    nombre varchar(50) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=INNODB;
/*CREAR TABLA USUARIO PARA RELACIONAR CON ROL*/
CREATE TABLE IF NOT EXISTS usuario(
    id int NOT NULL AUTO_INCREMENT,
    nombre varchar(50) NOT NULL,
    clave varchar(100) NOT NULL,
    rol_id int,
    PRIMARY KEY(id),
    FOREIGN KEY(rol_id) REFERENCES rol(id) ON DELETE RESTRIC ON UPDATE RESTRICT
)ENGINE=INNODB;